[tools]
bun = "1.4.2"
hk = "v2.1.0"
node = "24.20.0"

[tasks.setup]
run = """
bun install
hk install
"""

[tasks.dev]
run = "bun run astro dev"

[tasks.build]
run = "bun run astro build"

[tasks.preview]
run = "bun run astro preview"

[tasks.check]
run = "bun run check"

[tasks.fix]
run = "bun run fix"
